echo -e "\e[`expr $RANDOM % 7 + 31`;1m                             _.._        ,------------\e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m                          ,'      '.    ( We want you! \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m                         /  __) __' &    '-,----------\e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m                        (  ('-'(-')  ) _.-\e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m                        /)  &  = /  \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m                       /'    |--' .  \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m                      (  ,---|  '-.)__ _         \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m                       )(  '-.,--'   _'--)      \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m                      '/,'          (  Uu'-        \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m                       (_       ,    '/,-'            \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m                        .__,  : '-'/  /--        \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m                         |     -- ~   \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m                         ’   ‘-._  & \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m                          &        /\e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m                          /? .      &. \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m                         / |  &     ,-\e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m                        /  &| .)   /   }            \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m                       ( ,|&    ,'      )        \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m                       | &, . --’/      |       \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m                       ’,‘    &  |,'    \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m                      / ’-._   ‘-/      | \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m                      ‘-.   ’-.,'|     \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m                     /        _/[’---'‘’\e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m                    :        /  |‘-    | \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m                    ‘           |      /\e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m                                ’     & \e[0m"
