#!/usr/bin/expect
set timeout 60
spawn /usr/local/mysql/bin/mysql_secure_installation
expect {
  -re "enter for none" { send -- y\r;exp_continue; }
    -re "Y/n" { send -- y\r;exp_continue; }
      -re "password" { send -- bailaoda\r;exp_continue; }
        -re "password" { send -- bailaoda\r;exp_continue; }
	  -re "Y/n" { send -- n\r;exp_continue; }
	    -re "Y/n" { send -- n\r;exp_continue; }
	      -re "Y/n" { send -- y\r;exp_continue; }
	        -re "Y/n" { send -- y\r; }
		}
		exit
