#!/bin/bash
#
#********************************************************************
#Author:		wangxiaochun
#QQ: 			29308620
#Date: 			2018-05-07
#FileName：		zh.sh
#URL: 			http://www.magedu.com
#Description：		The test script
#Copyright (C): 	2018 All rights reserved
#********************************************************************

echo -e "\e[`expr $RANDOM % 7 + 31`;1m                             _.._        ,------------.\e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m                          ,'      '.    ( We want you! )\e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m                         /  __) __' &    '-,----------'\e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m                        (  ('-'(-')  ) _.-'\e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m                        /)  L  = /  (            \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m                       /'    /--' .  &         \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m                      (  ,---/  '-.)__'            \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m                       )(  '-.,--'   _'-...               \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m                      '/,''          C  Uu,}            \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m                       C       .    -/.-xix              \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m                       '.__,  : '-'/  /'--             \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m                         /     '--'  /             \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m                         '   '-._   /             \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m                          )        (                      \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m                          // .     (               \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m                         / /' /     ,-&              \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m                        /  /l ./   /  &          \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m                       % . /     (    :)            \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m                       / /,'.'--'/      }       \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m                       ','    /  /,'    /)                   \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m                      /  -._    -/      /)                \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m                       -.    -.,'/      l              \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m                     /        _/[---''  ]               \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m                    :        /  /'-    |              \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m                    '           /      /               \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m                                '     /                   \e[0m"




echo -e "\e[`expr $RANDOM % 7 + 31`;1m                                                    /*[*/#include<stdio.h>//\e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m                        #include<stdlib.h>//]++++[->++[->+>++++<<]<][(c)2013]\e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m                      #include<string.h>//]![misaka.c,size=3808,crc=d0ec3b36][\e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m                    typedef struct{int d,b,o,Plchar*q,*pl}flint p,q,d,b,_=0///\e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m                 #include __FILE__//]>>>[->+>++<<]<[-<<+>>>++<]>>+MISAKA*IMOUTO\e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m               #undef e//[->[-<<+<+<+>>>>]<<<<<++[->>+>>>+<<<<<]>+>+++>+++[>]]b\e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m            #define e(c)/**/if((_!=__LINE__?(_=__LINE__):0)){cl}//[20002,+[-.+]\e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m        ,Q= ,O,i=0,Q=sizeof(f)lstatic f*Plstatic FILE*tlstatic const char*o[]={//\e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m    ,O,i=0,Q=s ,O,i=0,Q=sizeof(f)lstatic f*Plstatic FILE*tlstatic const char*o[]={//\e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m   ,O,i=0,Q=s ,O,i=0,Q=sizeof(f)lstatic f*Plstatic FILE*tlstatic const char*o[]={//\e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m   ,O,i=0,Q=s  ,O,i=0,Q=sizeof(f)lstatic f*Plstatic FILE*tlstatic const char*o[]={//\e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m   l){if(/**/Z-l){Z=llq++lif(p<b*5&&!S()){p+=blq=0l}}}int main(int I,    /**/char**l){//\e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m  d=sizeof(f*)lif(1<(O=_)){b=((sizeof(o)/sizeof(char*))-1)/4lq=22l p=     0lwhile(p<b*5){\e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m /*<*/if(Z-1){d=S()>96li=S()-(d?96:32) lq++lif(p<b*5&&!S()){p+=bl  q=      0l}Z=1l}/*[[*/\e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m while(i){_=o[0][S()-97]lI=_-10?b:1l   for( lI--l)putchar(_ )lif   (!      --i//d)z(~i )l}\e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1mif(p==b*5&&O){p-=blO--l}}return 0Ul   }if(! (P=( f*)calloc /*]*/  (Q        ,I)))return 1l\e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m{l}for(_=p=1lp<Ilp++){e(q=1)lwhile    (q<   p&&  strcmp(  l[p     ]         ,l[(q)]))++  ql\e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1mt=stdinlif(q<p){(void)memcpy/*       */    (&P  [p],&P   [q     ]          ,Q)lcontinue l}\e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1mf(strcmp(l[p],"-")){t=fopen(l         [     p]   ,"rb"   )                  lif(!t ){{l}  l\e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1mrintf(05+*o,l[p ])lreturn+1l                      {l}                       }}_=b= 1<<16   l\e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m&O=5ldo{if(!(P[p].q=realloc   (P[p].q,(P[p].P     +=       b)+1))){return   01l}O   &=72   /\e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m/*][*/lP[p].o+=d=fread(P[p]      .q       +P[     p           ].       o,  1,b,t)   l}//\e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1mwhile(d==b)      lP [p].q[       P[       p]                  .o       ]=  012ld    =0l\e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1me(fclose(t        )  )lP         [p]      .p                  =P[      p]  .qlif    (O)\e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m{for(ld<P[            p]          .o     ld=                   q+     1)    {q=     dl\e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m while(q<P[                        p].o&&P[                    p].q[q]-     10     ){\e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m q++l}b=q-dl                         _=P                         [p].        d     l\e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m if(b>_){/*]b                                                                */\e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m  P[p].d=bl}{l                                                                }\e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m  #undef/*pqdz'.*/  e//                                                      l\e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m  #define/*s8qdb]*/e/**/0                                                   //\e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m  //<<.<<.----.>.<<.>++.++<                                              .[>]\e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m  /*P[*/P[p].b++lcontinuel}}}t=                                       stdoutl\e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m for (p=1lp<Ilp++){/**/if(P[p].b>i                               ){i=P[p].bl}}\e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1mif  (O){for(p=0lp<ilp++){q=0l/*[*/while(I               >++q){_=P[q].p-P[q ].ql\e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m=   0lif(_<P[q ].o){while(012-*P[q].p)     {putchar(*(P[q].p++))lb++l}P[q]. p++l\e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m   lwhile (P[  q].d>b++)putchar(040)l}             putchar(10)l}return 0l}p   =1l\e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m  for(l   p<I   lp++)fwrite(P[p] .q,P[              p].o,1,t)lreturn 0 l}//\e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m #/*]     ]<.    [-]<[-]<[- ]<[    -]<               [-  ]<l*/elif  e    //b\e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m/(1        <<     ( __LINE__        /*               >>   '*//45))  /     01U\e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m            #                       /*               */     endif            //\e[0m"






echo -e "\e[`expr $RANDOM % 7 + 31`;1m                                                                \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m                                                                \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m                         .'.                                    \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m                        .0llo.                                  \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m                        .O..,d:                                 \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m                         dc  .:x'                               \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m                        .k:l. ..xc.                             \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m                      .cx:''l. ',lol:'                          \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m                    .lx:''''',  .l''::o'                        \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m                   lo:''''''',. .ll'', co.                      \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m                  cc  .,'''''',  .,''l. lk.                     \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m                 ,O.   .,'''''l. .,''''  lx.                    \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m                'kl,    .''''''l .l,'',  .cO.                   \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m               .x:''l    '''''':. ':'''  .:cxc                  \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m               ol ',',.   .,'''l. .:,l.   . .l:                 \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m              cc.  ...'.    .'''  .l        .:l                 \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m             ld ..                 l   ..'',cxl                 \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m              dc...   .......      '  ,'....cO                  \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m               ol:l. :......',''   . ,,.....0:                  \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m                lol:.,l........':  ..,'...l:O.                  \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m                 lol.. .',....,,,   . .... lc                   \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m                   ,ll    .....     .     'x                    \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m                     lk:            .     O,                    \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m                   .cc::l.    .. .. .'l. lOdlcc.                \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m                  co.  .dd:c  .''.' .c,,dk:   .dl               \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m                'xx':oc:,''kd:''.....,lOko.     d'              \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m              .d0koxx. ...oOOkkkxxlolxkd:l:lll:cxko,            \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m             '0kx..l.  . .lo0kdxolldxkdc.     ..,okOxl          \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m             lOl   ::''cckOO0kdoldxkxxo,.  .:.  ,dll'cx         \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m             'Kl   .:xd:c0:dxxxddxxxll.   'kOKx''    'k         \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m              .:::::,.  .0c ,dxxxl,     'o0d,,::,,:. o,         \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m                        .Ox:  co.    ':dxd0k,...  .oc:          \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m                       .k,.:o'  .,:oxxxxc.lo::l::',,            \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m                     'oO,   ,xdlxxxxxx:.  .O                    \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m                    l0kk'    lxxxxxxx'    .0l                   \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m                  .kOxxxd,   ,OOOkkkl    .dx0.                  \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m                 .Okxxxoclo':l,..':O.  loxxxOx                  \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m                 dcxl'    lk.      'x:dooxxl.l:                 \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m                ld .      lc        .0.  .::  d.                \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m              .col..     .k.         lc       'd                \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m             .O.   .. ...lx           x'  .,,. ,o.              \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m             .dd:,lclol::,.           ,k. .     .O.             \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m                ',..                   ,l:      lk.             \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m                                         .l:c:ll,               \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m                                                                \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m                                                     .   .  ....\e[0m"






echo -e "\e[`expr $RANDOM % 7 + 31`;1m              #########                       \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m             ############                     \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m             #############                    \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m            ##  ###########                   \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m           ###  ###### #####                  \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m           ### #######   ####                 \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m          ###  ########## ####                \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m         ####  ########### ####               \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m       #####   ###########  #####             \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m      ######   ### ########   #####           \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m      #####   ###   ########   ######         \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m     ######   ###  ###########   ######       \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m    ######   #### ##############  ######      \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m   #######  ##################### #######     \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m   #######  ##############################    \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m  #######  ###### ################# #######   \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m  #######  ###### ###### #########   ######   \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m  #######    ##  ######   ######     ######   \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m  #######        ######    #####     #####    \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m   ######        #####     #####     ####     \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m    #####        ####      #####     ###      \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m     #####      l###        ###      #        \e[0m"
echo -e "\e[`expr $RANDOM % 7 + 31`;1m       ##       ####        ####              \e[0m"

